"""
Django settings for ResicaSMS project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sendgrid
from sendgrid.helpers.mail import *
from twilio.rest import Client

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Root of the Project
PROJECT_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            os.pardir)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'a%ea#9ihn11=e@n9gi6@0d26r61v+gh)6jui-=c4i2g52dw31e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'oanev.com',
    '178.128.155.35',
    '127.0.0.1'
]

# Application definition

INSTALLED_APPS = [
    'main.apps.MainConfig',
    'dashboard.apps.DashboardConfig',
    'user.apps.UserConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ResicaSMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ResicaSMS.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, '..', 'assets', 'static')
STATICFILES_DIRS = (
    os.path.join(PROJECT_ROOT, 'static'),
)

B64_DIGITS = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K',
                'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f',
                'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '-',
                '+']
# Groups
GROUPS = [
    ['stf', '6-15-18', '8-16-18'],
    ['dir', '6-8-18', '8-16-18'],
    ['stf', '5-18-18', '8-16-18'],
    ['wk1', '6-23-18', '6-29-18'],
    ['wk2', '6-30-18', '7-6-18'],
    ['wk3', '7-7-18', '7-13-18'],
    ['wk4', '7-14-18', '7-20-18'],
    ['wk5', '7-21-18', '7-27-18'],
    ['wk6', '7-28-18', '8-3-18'],
    ['wk7', '8-4-18', '8-10-18'],
]

# Joining text
INITIAL_TEXT = 'Welcome to the Resica Falls Texting Service. We will provide you with updates throughout your stay at ' \
               'camp. If you would like to stop receiving texts respond STOP '

# Set up Twilio
TWILIO_ACCOUNT_SID = "ACb7751a19f4658fe6ec8d4dc20b4bb5a3"
TWILIO_AUTH_TOKEN = "8bc98cb210a7cf49674b5749804fe5a9"
TWILIO_CLIENT = Client(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN)
TWILIO_PHONE_NUMBER = '+12156082357'

# Set up SendGrid
SENDGRID_API_KEY = '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'
SENDGRID_CLIENT = sendgrid.SendGridAPIClient(apikey=SENDGRID_API_KEY)
SENDGRID_FROM_EMAIL = Email("sms@resicafalls.org")

# Receipt recipients
RECEIPT_RECIPIENTS = [
    Email("pearatme@gmail.com"),
]
