# Generated by Django 2.0.7 on 2018-07-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=65)),
                ('salt', models.CharField(max_length=16)),
                ('powerlevel', models.IntegerField(default=0)),
            ],
        ),
    ]
