# Generated by Django 2.0.7 on 2018-07-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('unit', models.IntegerField(default=False)),
                ('timeframe', models.CharField(max_length=20)),
                ('offseason', models.BooleanField(default=False)),
            ],
        ),
    ]
