# Generated by Django 2.0.7 on 2018-07-08 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180708_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='offseason',
        ),
    ]
