# Generated by Django 2.0.7 on 2018-08-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=4)),
                ('username', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=16)),
                ('organizations', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
